### ISSUE TITLE
Inherit from fixtures in other files

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ecto_fixtures#25]
There could be default fixture data stored in another file. It would be ideal to be able to inherit that data rather than just the data in the same fixture file:

``` elixir
accounts model: Account, repo: Repo do
  brian inherits: from("accounts/valid").accounts.valid do
    name "Brian"
    dogs from(:dogs)
  end
end
```

**Comment by andreapavoni** [comment]
+1 for this ;-) having some reference to another model is a common case.
