### ISSUE TITLE
undefined function: EctoFixtures.fixtures/2

### ISSUE THREAD

**Issue by andreapavoni** [DockYard/ecto_fixtures#29]
Hi there,

I've just installed this package, however whenever I try to use `fixtures/2` function I always get an `undefined function` error. I've also tried to import the while module's functions instead of specify `only: [fixtures: 2]`, it didn't work.

No errors when I use `fixtures/1` function.

Any suggestions/hints?

**Comment by andreapavoni** [comment]
ok, solved by using the github version of this package. I didn't know `fixtures/2` wasn't present in the hex package until I've checked the imported functions :P

time to release v0.0.3? :-)

**Comment by bcardarella** [comment]
@apeacox yeah sorry, the release version is behind master. I have a few more issues I want to close before releasing

**Comment by andreapavoni** [comment]
thank you for the quick reply, @bcardarella! :-)

I'm converting my ugly poor-home-made fixtures with your package

feel free to close this issue :+1:

**Comment by bcardarella** [comment]
@apeacox awesome, let me know how it goes :)
