### ISSUE TITLE
Use Ecto 2.0's `insert_all` internally

### ISSUE THREAD

**Issue by poteto** [DockYard/ecto_fixtures#48]

**Comment by bcardarella** [comment]
I have given this consideration, I don't think this is going to be possible. Two reasons:
1. When inserting in batch, there will be no way to associate the records returned back from Ecto with their original fixture name. We could depend upon the generated primary key value, but we cannot always guarantee this. There could be a db trigger that fires and changes this value.
2. We use a DAG to do a topological sort on the association graph to ensure parents are inserted before children. Grouping these records properly to run batch insertions could be incredibly difficult and potentially very costly to calculate. I suspect more costly than the savings of batch insertion
