### ISSUE TITLE
** (UndefinedFunctionError) undefined function EctoFixtures.__using__/1

### ISSUE THREAD

**Issue by Qqwy** [DockYard/ecto_fixtures#49]
I am using:

Elixir 1.2.5
Erlang 18
Mix 1.2.5
Phoenix 1.1.4

Attempting to run tests after following the instructions in the Readme, results in the following error:

`** (UndefinedFunctionError) undefined function EctoFixtures.__using__/1`

It seems that `use EctoFixtures` is broken.

**Comment by bcardarella** [comment]
Can you provide an example of how you're using the library? If you can provide an example file that would be helpful

**Comment by bcardarella** [comment]
Oh wait, you may be trying to use what is on `master`. Can you try linking to `master` in your deps?

**Comment by Qqwy** [comment]
Thank you for your quick reply!

I see what I was doing wrong:

I was using version(0.0.2) on Hex.pm, that indeed is not up-to-date with the current state of the repository (although the version number of `master` has not been altered since).

Directly linking to github like this: 
`{:ecto_fixtures, "~> 0.0.2", only: [:dev, :test], github: 'DockYard/ecto_fixtures'}` resolves the problem.

**Comment by bcardarella** [comment]
I am waiting on Elixir 1.3 to drop for the next release. Sorry about that!

**Comment by bnymn** [comment]
Hi @bcardarella ,

Do you plan to make a release?
